### ISSUE TITLE
Developer Bootcamp — Logo failing to display

### ISSUE THREAD

**Issue by AaronFried** [Thinkful/bootcamp-finder#65]
Relevant screenshots:

https://www.dropbox.com/s/f6az1jyajg4tnrg/Screen%20Shot%202016-08-26%20at%206.04.14%20PM.png?dl=0

https://www.dropbox.com/s/j08ltslzludz75p/Screen%20Shot%202016-08-26%20at%206.04.04%20PM.png?dl=0

**Comment by jcudmore** [comment]
it has to do with the naming of the folder. this PR https://github.com/Thinkful/bootcamp-finder/pull/64 should fix, but releasing things for BF is tricky right now. cc: @tati @diezguerra

**Comment by tati** [comment]
fixed 
![screen shot 2016-09-07 at 3 07 28 pm](https://cloud.githubusercontent.com/assets/12241872/18324905/d2f5b18a-750c-11e6-9d3c-42b53779a922.png)
